apiVersion: apps/v1
kind: Deployment
metadata:
  name: sleep-server
  labels:
    app: sleep-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sleep-server
  template:
    metadata:
      labels:
        app: sleep-server
    spec:
      containers:
        - name: sleep-server
          image: faqiharifian/sleep-server:0.0.2
          ports:
            - containerPort: 8080
